# fly.toml app configuration file for staging environment (taucad.dev)
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tau-ui-staging'
primary_region = 'syd'

[build]
dockerfile = 'Dockerfile'

[env]
NODE_ENV = 'production'
TAU_API_URL = 'https://api.taucad.dev'
TAU_WEBSOCKET_URL = 'wss://api.taucad.dev'
TAU_FRONTEND_URL = 'https://taucad.dev'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

