import type { Drawing, Plane, Shape3D, Shell, Sketch } from 'replicad';
import {
  makeSolid,
  makeFace,
  assembleWire,
  EdgeFinder,
  draw,
  drawRoundedRectangle,
} from 'replicad';

export const defaultParams = {
  base: {
    width: 30,
    depth: 20,
    cornerRadius: 5,
  },
  profile: {
    line1X: 5,
    line1Y: 5,
    line2X: 2,
    line2Y: 3,
    bulgeArcX: 0,
    bulgeArcY: 1,
    bulgeFactor: 0.2,
  },
  brim: {
    width: 2,
    height: 1,
  },
};

function profileBox(inputProfile: Drawing, base: Drawing) {
  const start = inputProfile.blueprint.firstPoint;
  const profile = inputProfile.translate(-start[0], -start[1]);
  const end = profile.blueprint.lastPoint;
  const baseSketch = base.sketchOnPlane() as Sketch;

  // We create the side of the box
  const side = baseSketch.clone().sweepSketch(
    (plane: Plane): Sketch => {
      return profile.sketchOnPlane(plane) as Sketch;
    },
    {
      withContact: true,
    },
  ) as Shell;

  // We put all the pieces together
  return makeSolid([
    side,
    // The face generated by sweeping the end of the profile
    makeFace(assembleWire(new EdgeFinder().inPlane('XY', end[1]).find(side))),
    // The face generated by the base
    baseSketch.face(),
  ]);
}

export default function main(p = defaultParams): Shape3D {
  const base = drawRoundedRectangle(
    p.base.width,
    p.base.depth,
    p.base.cornerRadius,
  );

  const profile = draw()
    .line(p.profile.line1X, p.profile.line1Y)
    .line(p.profile.line2X, p.profile.line2Y)
    .hLine(-p.brim.width)
    .vLine(-p.brim.height)
    .bulgeArcTo(
      [p.profile.bulgeArcX, p.profile.bulgeArcY],
      p.profile.bulgeFactor,
    )
    .done();

  return profileBox(profile, base);
}
