import { X509Certificate } from 'node:crypto';
import { readFileSync } from 'node:fs';

const mkcertCnPattern = /(?:^|,\s*)CN=([^,]+)/u;

/** Pull mkcert CN from PEM `subject` (e.g. `mkcert user@hostname`). */
const readCnFromCertificateSubject = (pemUtf8: string): undefined | string => {
  try {
    const certificate = new X509Certificate(pemUtf8.trim());
    const capture = mkcertCnPattern.exec(certificate.subject);
    const commonName = capture?.[1]?.trim();
    return commonName !== undefined && commonName.length > 0 ? commonName : undefined;
  } catch {
    return undefined;
  }
};

/** Parse CA PEM without touching the filesystem (tests). */
export const readDevRootCommonNameFromCertificatePem = (pemUtf8: string): string =>
  readCnFromCertificateSubject(pemUtf8) ?? 'the mkcert dev CA';

/** Read CN from workspace `rootCA.pem` generated by vite-plugin-mkcert / nx bootstrap. */
export const readDevRootCommonName = (caPemPath: string): string =>
  readDevRootCommonNameFromCertificatePem(readFileSync(caPemPath, 'utf8'));

/** Indent every line of the rendered QR (or any multi-line block) by 2 spaces so it lines up with the rationale + steps copy. */
export const indentBannerBlock = (block: string): string =>
  block
    .split('\n')
    .map((line) => (line.length === 0 ? line : `  ${line}`))
    .join('\n');

export type IosTrustBannerInput = {
  readonly httpsUrl: string;
  readonly rootCommonName: string;
};

const dividerLine = `${'─'.repeat(67)}`;

/**
 * Header (rule + headline + rationale) and steps (numbered iOS checklist).
 * QR codes are rendered by the caller between `header` and `steps` so we can
 * stream `qrcode-terminal` output directly to stdout without buffering it.
 */
export const formatIosTrustBanner = (
  input: IosTrustBannerInput,
): { readonly header: string; readonly steps: string } => {
  const header = [
    '',
    dividerLine,
    '  Trust the mkcert dev CA on iOS / iPadOS (one time, ~30 s)',
    dividerLine,
    '',
    '  Why?  Tau runs CAD kernels and geometry transports through',
    '        SharedArrayBuffer for zero-copy speed. Browsers only',
    '        expose SharedArrayBuffer when the page is cross-origin',
    '        isolated, which requires HTTPS on every non-loopback',
    '        origin (Safari included). Trusting this local CA lets',
    `        your phone load ${input.httpsUrl} without`,
    '        the "Connection Is Not Private" interstitial, so',
    '        SharedArrayBuffer-backed kernels load on the device.',
    '',
    '        Background: https://tau.new/docs/runtime/guides/cross-origin-isolation',
    '',
  ].join('\n');

  const steps = [
    '',
    `  1. Tap "Allow" when Safari prompts to download the profile`,
    `  2. Settings -> General -> VPN & Device Management`,
    `       -> ${input.rootCommonName} -> Install (enter passcode)`,
    `  3. Settings -> General -> About -> Certificate Trust Settings`,
    `       -> toggle "${input.rootCommonName}" ON  (this step is required)`,
    `  4. Reload ${input.httpsUrl} in Safari`,
    '',
    dividerLine,
    '',
  ].join('\n');

  return { header, steps };
};

export type QrCaptionInput = {
  readonly extraUrls?: readonly string[];
  readonly headline: string;
  readonly url: string;
};

/**
 * Caption to render directly under a QR code. Single-line "headline · url"
 * keeps both QRs scannable at a glance, with optional extra LAN URLs listed
 * underneath when `--host` resolves to multiple interfaces.
 */
export const formatQrCaption = (input: QrCaptionInput): string => {
  const extraUrls = input.extraUrls ?? [];
  const lines = [`  ${input.headline}  ·  ${input.url}`];
  if (extraUrls.length > 0) {
    lines.push('  Other LAN URLs:');
    for (const url of extraUrls) {
      lines.push(`    ${url}`);
    }
  }
  return lines.join('\n');
};
