/* eslint-disable @typescript-eslint/naming-convention -- required for the precompiled grammar */
/* eslint-disable no-useless-escape -- required for the precompiled grammar */
/**
 * Precompiled STEP file language for Shiki.
 *
 * This is a precompiled version of the STEP file language for Shiki.
 * It is used to highlight STEP file code in the Monaco editor.
 *
 * This file is generated by a custom script:
 * `npx tsx precompile-grammar.ts ./apps/ui/app/lib/stepfile-language/stepfile.tmLanguage.json`
 *
 * @see https://github.com/taucad/shiki/blob/main/README-precompile.md
 *
 * The original Textmate grammar is sourced from: https://github.com/mjecke/step-file-syntax/blob/main/syntaxes/stepfile.tmLanguage.json
 *
 * TODO: add the original grammar to the Shiki project.
 */

const lang = Object.freeze({
  name: 'stepfile',
  scopeName: 'source.step',
  displayName: 'stepfile',
  fileTypes: ['stepfile'],
  aliases: undefined,
  patterns: [
    { include: '#keywords' },
    { include: '#string-double-quoted' },
    { include: '#string-single-quoted' },
    { include: '#escaped-char' },
    { include: '#comments' },
    { include: '#variables' },
    { name: 'entity.name.class.step', match: /[a-zA-Z_][\-\p{L}\p{M}\p{N}\p{Pc}]*/dgv },
    { name: 'constant.numeric.step', match: /[\-\+]?\p{Nd}+(\.\p{Nd}+)?/dgv },
  ],
  repository: {
    keywords: {
      patterns: [
        {
          name: 'keyword.control.step',
          match:
            /\b(FILE_NAME|file_name|FILE_DESCRIPTION|file_description|FILE_SCHEMA|file_schema|FILE_POPULATION|file_population|SECTION_LANGUAGE|section_language|SECTION_CONTEXT|section_context)\b/dgv,
        },
        { name: 'keyword.other.step', match: /\b(HEADER|header|ENDSEC|endsec|DATA|data)\b/dgv },
      ],
    },
    variables: { patterns: [{ match: /\b(ISO-10303-21|END-ISO-10303-21)\b/dgv, name: 'variable.other.step' }] },
    'string-double-quoted': {
      begin: /"/dgv,
      beginCaptures: [{ name: 'punctuation.definition.string.begin.step' }],
      end: /"/dgv,
      endCaptures: [{ name: 'punctuation.definition.string.end.step' }],
      name: 'string.quoted.double.step',
      patterns: [{ include: '#escaped-char' }],
    },
    'string-single-quoted': {
      begin: /'/dgv,
      beginCaptures: [{ name: 'punctuation.definition.string.begin.step' }],
      end: /'/dgv,
      endCaptures: [{ name: 'punctuation.definition.string.end.step' }],
      name: 'string.quoted.single.step',
      patterns: [{ include: '#escaped-char' }],
    },
    'escaped-char': {
      name: 'constant.character.escape.step',
      patterns: [{ match: /\\(x\p{AHex}{2}|n|r|t|0|"|''|\\|u\{\p{AHex}{1,6}\})/dgv }],
    },
    comments: {
      patterns: [
        {
          begin: /\/\*/dgv,
          end: /\*\//dgv,
          beginCaptures: { 0: { name: 'punctuation.definition.comment.begin.step' } },
          endCaptures: { 0: { name: 'punctuation.definition.comment.end.step' } },
          name: 'comment.block.step',
        },
      ],
    },
  },
  embeddedLangs: [],
});

const langs = [lang];

export default langs;
