import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it, expect, beforeAll } from 'vitest';

/**
 * Tests for the replicad bundled type declarations.
 *
 * Verifies that the generated output has the correct structure:
 * - Raw module `.d.ts` content (no `declare module` wrapper)
 * - All exported classes, functions, types, and interfaces are present
 * - Imports from replicad-opencascadejs are preserved
 */

let output: string;

beforeAll(() => {
  const jsonPath = join(import.meta.dirname, 'generated/replicad/replicad.bundled.json');
  const modules = JSON.parse(readFileSync(jsonPath, 'utf8')) as Record<string, string>;
  output = modules['replicad']!;
});

describe('extract-replicad-types', () => {
  // ---------------------------------------------------------------------------
  // Raw module format (no declare module wrapper)
  // ---------------------------------------------------------------------------

  it('does not contain a declare module wrapper', () => {
    expect(output).not.toContain("declare module 'replicad'");
  });

  it('starts with a generated header comment', () => {
    expect(output).toContain('Auto-generated by extract-replicad-api.ts');
  });

  // ---------------------------------------------------------------------------
  // Imports
  // ---------------------------------------------------------------------------

  it('preserves replicad-opencascadejs imports', () => {
    expect(output).toContain("import { gp_Pnt } from 'replicad-opencascadejs'");
    expect(output).toContain("import { TopoDS_Shape } from 'replicad-opencascadejs'");
  });

  it('preserves opentype.js import', () => {
    expect(output).toContain("from 'opentype.js'");
  });

  // ---------------------------------------------------------------------------
  // Core classes
  // ---------------------------------------------------------------------------

  it('exports Shape3D class', () => {
    expect(output).toContain('export declare class _3DShape<Type extends TopoDS_Shape>');
  });

  it('exports Drawing class', () => {
    expect(output).toContain('export declare class Drawing');
  });

  it('exports Solid class', () => {
    expect(output).toContain('export declare class Solid extends _3DShape<TopoDS_Solid>');
  });

  it('exports Face class', () => {
    expect(output).toContain('export declare class Face extends Shape<TopoDS_Face>');
  });

  it('exports Edge class', () => {
    expect(output).toContain('export declare class Edge extends _1DShape<TopoDS_Edge>');
  });

  it('exports Blueprint class', () => {
    expect(output).toContain('export declare class Blueprint implements DrawingInterface');
  });

  it('exports Sketcher class', () => {
    expect(output).toContain('export declare class Sketcher');
  });

  // ---------------------------------------------------------------------------
  // Core functions
  // ---------------------------------------------------------------------------

  it('exports draw function', () => {
    expect(output).toContain('export declare function draw(');
  });

  it('exports drawCircle function', () => {
    expect(output).toContain('export declare function drawCircle(');
  });

  it('exports drawRoundedRectangle function', () => {
    expect(output).toContain('export declare function drawRoundedRectangle(');
  });

  it('exports makeSolid function', () => {
    expect(output).toContain('export declare function makeSolid(');
  });

  it('exports cast function', () => {
    expect(output).toContain('export declare function cast(');
  });

  // ---------------------------------------------------------------------------
  // Types and interfaces
  // ---------------------------------------------------------------------------

  it('exports Point type', () => {
    expect(output).toContain('export declare type Point =');
  });

  it('exports Point2D type', () => {
    expect(output).toContain('export declare type Point2D =');
  });

  it('exports AnyShape union type', () => {
    expect(output).toContain('export declare type AnyShape =');
  });

  it('exports DrawingInterface', () => {
    expect(output).toContain('export declare interface DrawingInterface');
  });
});
