#!/usr/bin/env node

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

/**
 * Bundle opencascade.js type declarations as raw `.d.ts` for Monaco's
 * `addExtraLib`.
 *
 * Reads the generated `opencascade_full.d.ts` (produced by the opencascade.js
 * build pipeline in `buildFromYaml.py`) and outputs a raw module `.d.ts`
 * (no `declare module` wrapper).
 *
 * The OCJS codegen now emits a structurally complete `.d.ts` — every referenced
 * type is declared (R3 routes unbound spellings to `unknown` at the bindings
 * layer) and namespace convenience blocks were removed wholesale (R10). This
 * file is therefore a thin pass-through; previous post-processing for stub
 * generation and namespace stripping is dead code.
 *
 * Monaco registers the output at `file:///node_modules/opencascade.js/index.d.ts`
 * and relies on standard TypeScript module resolution — `export declare` is
 * valid and correct in this context.
 */

// =============================================================================
// Configuration
// =============================================================================

const opencascadeDtsPath = join(
  import.meta.dirname,
  '../../../packages/runtime/src/kernels/opencascade/wasm/opencascade_full.d.ts',
);

// =============================================================================
// Transformation
// =============================================================================

/**
 * Read the raw `opencascade_full.d.ts` and return its trimmed content.
 *
 * @returns The type declarations as a raw module `.d.ts`.
 */
function buildMainContent(): string {
  const content = readFileSync(opencascadeDtsPath, 'utf8').replace(/\nexport\s*{\s*}\s*$/, '');
  return content.trim();
}

// =============================================================================
// Output
// =============================================================================

/**
 * Build the bundled type declarations as a map of module path to raw `.d.ts`
 * content. Each entry is registered at its own virtual file path in Monaco.
 * Exported for testing.
 */
export function buildBundledTypes(): Record<string, string> {
  const mainPackage = 'opencascade.js';

  return {
    [mainPackage]: [
      '// Bundled type declarations for opencascade.js.',
      '// Auto-generated by extract-opencascade-types.ts - do not edit manually.',
      '',
      buildMainContent(),
      '',
    ].join('\n'),
  };
}

// =============================================================================
// Main
// =============================================================================

function main(): void {
  try {
    console.log('Extracting opencascade.js type declarations...\n');

    const outputDirectory = join(import.meta.dirname, 'generated/opencascade');
    mkdirSync(outputDirectory, { recursive: true });
    console.log(`Output directory: ${outputDirectory}`);

    const bundledTypes = buildBundledTypes();
    const outputPath = join(outputDirectory, 'opencascade.bundled.json');
    writeFileSync(outputPath, JSON.stringify(bundledTypes));
    console.log(`\nBundled type declarations written to ${outputPath}`);
    for (const [name, content] of Object.entries(bundledTypes)) {
      console.log(`  - ${name} (${(content.length / 1024 / 1024).toFixed(1)} MB)`);
    }

    // Write individual .d.ts files for type-level testing
    const modulesDirectory = join(outputDirectory, 'modules');
    for (const [modulePath, content] of Object.entries(bundledTypes)) {
      const targetDirectory = join(modulesDirectory, modulePath);
      mkdirSync(targetDirectory, { recursive: true });
      writeFileSync(join(targetDirectory, 'index.d.ts'), content);
    }

    console.log('\nopencascade.js type extraction completed successfully!');
  } catch (error) {
    console.error('Error during opencascade.js type extraction:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
