#!/usr/bin/env node

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import process from 'node:process';

/**
 * Bundle opencascade.js type declarations as raw `.d.ts` for Monaco's
 * `addExtraLib`.
 *
 * Reads the generated `opencascade_full.d.ts` (produced by the opencascade.js
 * build pipeline in `buildFromYaml.py`), strips namespace convenience aliases
 * to reduce size, generates stubs for undeclared C++ types referenced in
 * signatures, and outputs a raw module `.d.ts` (no `declare module` wrapper).
 *
 * Monaco registers the output at `file:///node_modules/opencascade.js/index.d.ts`
 * and relies on standard TypeScript module resolution — `export declare` is
 * valid and correct in this context.
 *
 * A separate alias file is generated so `import ... from 'opencascade'` also
 * resolves.
 */

// =============================================================================
// Configuration
// =============================================================================

const opencascadeDtsPath = join(
  import.meta.dirname,
  '../../../packages/kernels/src/kernels/opencascade/wasm/opencascade_full.d.ts',
);

// =============================================================================
// Undeclared Type Stub Generation
// =============================================================================

/**
 * Scan the `.d.ts` content for types referenced in signatures (parameter
 * types, return types, `extends` clauses) that are never declared. These are
 * OCCT-internal C++ types not bound by Embind. Returns the list of names so
 * callers can prepend `export type X = unknown;` stubs.
 */
function findUndeclaredTypes(content: string): string[] {
  const declared = new Set<string>();
  for (const m of content.matchAll(
    /(?:export\s+declare\s+class|export\s+class|export\s+type|export\s+declare\s+const|export\s+const)\s+(\w+)/g,
  )) {
    if (m[1]) {
      declared.add(m[1]);
    }
  }

  const referenced = new Set<string>();
  const lines = content.split('\n');
  for (const line of lines) {
    const stripped = line.trim();
    if (stripped.startsWith('*') || stripped.startsWith('//')) {
      continue;
    }

    for (const m of line.matchAll(/:\s*(\w+(?:_\w+)+)\b/g)) {
      const name = m[1]!;
      if (name[0]! >= 'A' && name[0]! <= 'Z') {
        referenced.add(name);
      }
    }
    for (const m of line.matchAll(/extends\s+(\w+(?:_\w+)+)\b/g)) {
      const name = m[1]!;
      if (name[0]! >= 'A' && name[0]! <= 'Z') {
        referenced.add(name);
      }
    }
  }

  const undeclared = [...referenced].filter((name) => !declared.has(name)).sort();
  return undeclared;
}

// =============================================================================
// Transformation
// =============================================================================

/**
 * Read and transform the raw `opencascade_full.d.ts` into cleaned content.
 * Strips namespace aliases and trailing empty exports, then prepends stubs
 * for undeclared types.
 *
 * @returns The transformed type declarations as a raw module `.d.ts`.
 */
function buildMainContent(): string {
  let content = readFileSync(opencascadeDtsPath, 'utf8');

  // Strip namespace convenience alias blocks (e.g. `export namespace BRep { ... }`)
  content = content.replaceAll(/^export namespace \w+ {[\S\s]*?^}\n\n/gm, '');

  // Strip trailing `export { }` if present
  content = content.replace(/\nexport\s*{\s*}\s*$/, '');

  // Generate stubs for undeclared types referenced in signatures
  const stubs = findUndeclaredTypes(content);
  if (stubs.length > 0) {
    const stubBlock = stubs.map((t) => `export type ${t} = unknown;`).join('\n');
    content = stubBlock + '\n\n' + content;
  }

  return content.trim();
}

// =============================================================================
// Output
// =============================================================================

/**
 * Build the bundled type declarations as a map of module path to raw `.d.ts`
 * content. Each entry is registered at its own virtual file path in Monaco.
 * Exported for testing.
 */
export function buildBundledTypes(): Record<string, string> {
  const mainPackage = 'opencascade.js';
  const aliasPackage = 'opencascade';

  return {
    [mainPackage]: [
      '// Bundled type declarations for opencascade.js.',
      '// Auto-generated by extract-opencascade-types.ts - do not edit manually.',
      '',
      buildMainContent(),
      '',
    ].join('\n'),
    [aliasPackage]: [
      '// Re-export alias so `import ... from "opencascade"` resolves.',
      '// Auto-generated by extract-opencascade-types.ts - do not edit manually.',
      '',
      "export * from 'opencascade.js';",
      "export { default } from 'opencascade.js';",
      '',
    ].join('\n'),
  };
}

// =============================================================================
// Main
// =============================================================================

function main(): void {
  try {
    console.log('Extracting opencascade.js type declarations...\n');

    const outputDirectory = join(import.meta.dirname, 'generated/opencascade');
    mkdirSync(outputDirectory, { recursive: true });
    console.log(`Output directory: ${outputDirectory}`);

    const bundledTypes = buildBundledTypes();
    const outputPath = join(outputDirectory, 'opencascade.bundled.json');
    writeFileSync(outputPath, JSON.stringify(bundledTypes));
    console.log(`\nBundled type declarations written to ${outputPath}`);
    for (const [name, content] of Object.entries(bundledTypes)) {
      console.log(`  - ${name} (${(content.length / 1024 / 1024).toFixed(1)} MB)`);
    }

    // Write individual .d.ts files for type-level testing
    const modulesDirectory = join(outputDirectory, 'modules');
    for (const [modulePath, content] of Object.entries(bundledTypes)) {
      const targetDirectory = join(modulesDirectory, modulePath);
      mkdirSync(targetDirectory, { recursive: true });
      writeFileSync(join(targetDirectory, 'index.d.ts'), content);
    }

    console.log('\nopencascade.js type extraction completed successfully!');
  } catch (error) {
    console.error('Error during opencascade.js type extraction:', error);
    process.exit(1);
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
