packages:
  - apps/*
  - libs/*
  - packages/*

catalog:
  '@ai-sdk/provider-utils': ^4.0.15
  '@arethetypeswrong/cli': ^0.18.2
  '@eslint-community/eslint-plugin-eslint-comments': ^4.7.1
  '@gltf-transform/core': ^4.3.0
  '@gltf-transform/extensions': ^4.3.0
  '@gltf-transform/functions': ^4.3.0
  '@inkjs/ui': ^2.0.0
  '@jscad/modeling': ^2.13.0
  '@kittycad/lib': ^2.0.48
  '@langchain/anthropic': ^1.3.20
  '@langchain/cerebras': ^1.0.2
  '@langchain/classic': ^1.0.20
  '@langchain/community': ^1.1.19
  '@langchain/core': ^1.1.28
  '@langchain/google-vertexai': ^2.1.20
  '@langchain/langgraph': ^1.1.5
  '@langchain/langgraph-checkpoint': ^1.0.0
  '@langchain/langgraph-checkpoint-postgres': ^1.0.1
  '@langchain/ollama': ^1.2.4
  '@langchain/openai': ^1.2.10
  '@langchain/tavily': ^1.2.0
  '@msgpack/msgpack': ^3.1.3
  '@nx/devkit': 22.5.2
  '@nx/eslint': 22.5.2
  '@nx/eslint-plugin': 22.5.2
  '@nx/js': 22.5.2
  '@nx/nest': 22.5.2
  '@nx/node': 22.5.2
  '@nx/playwright': 22.5.2
  '@nx/react': 22.5.2
  '@nx/vite': 22.5.2
  '@nx/web': 22.5.2
  '@nx/webpack': 22.5.2
  '@playwright/test': ^1.58.2
  '@react-router/dev': 7.12.0
  '@react-router/fs-routes': 7.12.0
  '@react-router/node': 7.12.0
  '@react-router/serve': 7.12.0
  '@taucad/kcl-wasm-lib': 0.1.111
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.2.0
  '@types/js-yaml': ^4.0.9
  '@types/json-schema': ^7.0.15
  '@types/madge': ^5.0.3
  '@types/node': ~24.0.15
  '@types/react': 19.0.12
  '@types/react-dom': 19.0.4
  '@typescript/native-preview': 7.0.0-dev.20260223.1
  '@vitest/coverage-v8': 4.0.9
  '@vitest/ui': 4.0.9
  '@zenfs/core': ^2.5.0
  '@zenfs/dom': ^1.2.7
  cdn-resolve: ^2.1.2
  comlink: ^4.4.2
  culori: ^4.0.2
  deepmerge: ^4.3.1
  dotenv: ^17.3.1
  es-module-lexer: ^2.0.0
  esbuild-wasm: ^0.27.3
  eslint: 9.32.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^62.7.1
  eslint-plugin-max-params-no-constructor: ^0.0.4
  eslint-plugin-n: ^17.24.0
  eslint-plugin-no-use-extend-native: ^0.7.2

  eslint-plugin-react: ^7.37.5
  eslint-plugin-unicorn: ^63.0.0
  geist: ^1.7.0
  ink: ^6.8.0
  isbot: ^5.1.35
  js-yaml: ^4.1.1
  json-schema-default: ^1.0.2
  langchain: ^1.2.27
  madge: ^8.0.0
  manifold-3d: 3.3.2
  mermaid: ^11.12.3
  nx: 22.5.2
  openscad-wasm-prebuilt: ^1.2.0
  oxfmt: ^0.36.0
  oxlint: ^1.51.0
  oxlint-tsgolint: ^0.16.0

  publint: ^0.3.17
  react: ^19.2.4
  react-dom: ^19.2.4
  react-router: 7.12.0
  replicad: /Users/rifont/git/tau/tarballs/experiments/v8-O3-noLTO-wasmOptO3-maxperf/replicad-0.21.0-v8.7.tgz
  replicad-opencascadejs: /Users/rifont/git/tau/tarballs/experiments/v8-O3-noLTO-wasmOptO3-maxperf/replicad-opencascadejs-0.21.0-v8.25.tgz
  source-map-js: ^1.2.1
  tsdown: ^0.15.12
  tslib: ^2.8.1
  type-fest: ^4.41.0
  typescript: ~5.9.3
  typescript-eslint: ^8.56.1
  uint8array-extras: ^1.5.0
  uzip: ^0.20201231.0
  vite: ~7.0.8
  vitest: 4.0.9
  ws: ^8.19.0
  xstate: ^5.28.0
  zod: ^4.3.6

catalogMode: prefer
