packages:
  - apps/*
  - libs/*
  - packages/*

catalog:
  '@arethetypeswrong/cli': ^0.18.2
  '@gltf-transform/core': ^4.3.0
  '@gltf-transform/extensions': ^4.3.0
  '@gltf-transform/functions': ^4.3.0
  '@jscad/modeling': ^2.12.6
  '@kittycad/lib': ^2.0.42
  '@msgpack/msgpack': ^3.1.2
  '@nx/devkit': 21.3.10
  '@nx/eslint': 21.3.10
  '@nx/eslint-plugin': 21.3.10
  '@nx/js': 21.3.10
  '@nx/nest': 21.3.10
  '@nx/node': 21.3.10
  '@nx/playwright': 21.3.10
  '@nx/react': 21.3.10
  '@nx/vite': 21.3.10
  '@nx/web': 21.3.10
  '@nx/webpack': 21.3.10
  '@react-router/dev': ^7.9.6
  '@react-router/fs-routes': ^7.9.6
  '@react-router/node': ^7.9.6
  '@react-router/serve': ^7.9.6
  '@taucad/kcl-wasm-lib': 0.1.111
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.2.0
  '@types/json-schema': ^7.0.15
  '@types/madge': ^5.0.3
  '@types/node': ~24.0.15
  '@types/react': 19.0.12
  '@types/react-dom': 19.0.4
  '@vitest/coverage-v8': 3.2.4
  '@vitest/ui': 3.2.4
  '@zenfs/core': ^2.4.4
  '@zenfs/dom': ^1.2.7
  assimpjs: https://codeload.github.com/taucad/assimpjs/tar.gz/bc10b475fd4cb632239b226f11222c86e8763fc6
  cdn-resolve: ^2.1.2
  comlink: ^4.4.2
  culori: ^4.0.2
  deepmerge: ^4.3.1
  es-module-lexer: ^2.0.0
  esbuild-wasm: ^0.27.2
  eslint: 9.32.0
  eslint-plugin-jsdoc: ^62.7.0
  eslint-plugin-max-params-no-constructor: ^0.0.4
  geist: ^1.5.1
  isbot: ^5.1.28
  json-schema-default: ^1.0.2
  madge: ^8.0.0
  nx: 21.3.10
  openscad-wasm-prebuilt: ^1.2.0
  prettier: 3.4.2
  publint: ^0.3.17
  react: ^19.0.0
  react-dom: ^19.0.0
  react-router: ^7.9.6
  replicad: ^0.19.1
  replicad-opencascadejs: ^0.19.0
  source-map-js: ^1.2.1
  tsdown: ^0.15.7
  tslib: ^2.8.1
  type-fest: ^4.35.0
  typescript: ~5.9.3
  uint8array-extras: ^1.4.0
  uzip: ^0.20201231.0
  vite: ^7.0.6
  vitest: 3.2.4
  ws: ^8.18.3
  xstate: ^5.24.0
  zod: ^4.1.13

catalogMode: prefer
