export const codeLanguages = {
  typescript: 'typescript',
  kcl: 'kcl',
  openscad: 'openscad',
  stepfile: 'stepfile',
  stl: 'stl',
  usd: 'usd',
  javascript: 'javascript',
  jsx: 'jsx',
  tsx: 'tsx',
  bash: 'bash',
  json: 'json',
} as const;

export const languageFromExtension = {
  kcl: 'kcl',
  scad: 'openscad',
  step: 'stepfile',
  stp: 'stepfile',
  p21: 'stepfile',
  stl: 'stl',
  usd: 'usd',
  usda: 'usd',
  usdc: 'usd',
  usdz: 'usd',
  js: 'javascript',
  jsx: 'jsx',
  ts: 'typescript',
  tsx: 'tsx',
  sh: 'bash',
  json: 'json',
} as const;
