/* eslint-disable prettier/prettier -- Auto-generated code. */
// AUTO-GENERATED by scripts/generate-manifest.ts — DO NOT EDIT.
// Run `pnpm nx generate-manifest tau-examples` to regenerate.

/** Map of kernel names to their available example fixture names. */
export type ExampleManifest = {
  jscad: 'cube' | 'cylinder' | 'gear';
  replicad: 'birdhouse' | 'bottle' | 'card-holder' | 'chair' | 'cycloidal-gear' | 'decorated-box' | 'drinking-glass' | 'gridfinity-box' | 'hex-screwdriver' | 'hollow-box' | 'ibeam' | 'lego' | 'pot-plant' | 'projection-test' | 'simple-tray' | 'staircase' | 'stress-test' | 't-slot-rail' | 'table' | 'tray' | 'vase' | 'wavy-vase';
};

/** Available kernel names. */
export type KernelName = keyof ExampleManifest;

/** Available example names for a given kernel. */
export type ExampleName<K extends KernelName> = ExampleManifest[K];
