/* eslint-disable no-useless-escape -- required for the precompiled grammar */
/* eslint-disable @typescript-eslint/naming-convention -- required for the precompiled grammar */
/**
 * Precompiled STL (Stereolithography) language for Shiki.
 *
 * This is a precompiled version of the STL language for Shiki.
 * It is used to highlight ASCII STL 3D geometry files in the Monaco editor.
 *
 * This file is generated by a custom script:
 * `npx tsx precompile-grammar.ts ./apps/ui/app/lib/stl-language/stl.tmLanguage.json`
 *
 * @see https://github.com/taucad/shiki/blob/main/README-precompile.md
 * @see https://en.wikipedia.org/wiki/STL_(file_format)
 *
 * TODO: add the original grammar to the Shiki project.
 */

const lang = Object.freeze({
  name: 'stl',
  scopeName: 'source.stl',
  displayName: 'stl',
  fileTypes: ['stl'],
  aliases: undefined,
  patterns: [
    { include: '#solid' },
    { include: '#endsolid' },
    { include: '#facetNormal' },
    { include: '#endfacet' },
    { include: '#outerLoop' },
    { include: '#endloop' },
    { include: '#vertex' },
    { include: '#numbers' },
  ],
  repository: {
    solid: {
      comment: 'solid <name>',
      match: /^\p{space}*(solid)\b\p{space}*([^\n]*?)\p{space}*(?=\n?$)/dgv,
      captures: { '1': { name: 'keyword.control.solid.stl' }, '2': { name: 'entity.name.type.solid.stl' } },
    },
    endsolid: {
      comment: 'endsolid [name]',
      match: /^\p{space}*(endsolid)\b\p{space}*([^\n]*?)\p{space}*(?=\n?$)/dgv,
      captures: { '1': { name: 'keyword.control.endsolid.stl' }, '2': { name: 'entity.name.type.solid.stl' } },
    },
    facetNormal: {
      comment: 'facet normal <nx> <ny> <nz>',
      match:
        /^\p{space}*(facet)\p{space}+(normal)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)/dgv,
      captures: {
        '1': { name: 'keyword.control.facet.stl' },
        '2': { name: 'keyword.other.normal.stl' },
        '3': { name: 'constant.numeric.float.stl' },
        '4': { name: 'constant.numeric.float.stl' },
        '5': { name: 'constant.numeric.float.stl' },
      },
    },
    endfacet: { name: 'keyword.control.endfacet.stl', match: /\b(endfacet)\b/dgv },
    outerLoop: {
      match: /^\p{space}*(outer)\p{space}+(loop)\p{space}*(?=\n?$)/dgv,
      captures: { '1': { name: 'keyword.control.outer.stl' }, '2': { name: 'keyword.control.loop.stl' } },
    },
    endloop: { name: 'keyword.control.endloop.stl', match: /\b(endloop)\b/dgv },
    vertex: {
      comment: 'vertex <x> <y> <z>',
      match:
        /^\p{space}*(vertex)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)\p{space}+([\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?)/dgv,
      captures: {
        '1': { name: 'storage.type.vertex.stl' },
        '2': { name: 'constant.numeric.float.stl' },
        '3': { name: 'constant.numeric.float.stl' },
        '4': { name: 'constant.numeric.float.stl' },
      },
    },
    numbers: { name: 'constant.numeric.float.stl', match: /[\-\+]?[0-9]*\.?[0-9]+(?:[eE][\-\+]?[0-9]+)?\b/dgv },
  },
  embeddedLangs: [],
});

const langs = [lang];

export default langs;
