/* eslint-disable no-useless-escape -- required for the precompiled grammar */
/* eslint-disable @typescript-eslint/naming-convention -- required for the precompiled grammar */
/**
 * Precompiled USD (Universal Scene Description) language for Shiki.
 *
 * This is a precompiled version of the USD language for Shiki.
 * It is used to highlight USD code in the Monaco editor.
 *
 * This file is generated by a custom script:
 * `npx tsx precompile-grammar.ts ./apps/ui/app/lib/usd-language/usd.tmLanguage.json`
 *
 * @see https://github.com/taucad/shiki/blob/main/README-precompile.md
 *
 * The original Textmate grammar is sourced from:
 * - https://github.com/AnimalLogic/AL_usd_vscode_extension/blob/master/syntaxes/usd.tmLanguage.json
 *
 * TODO: add the original grammar to the Shiki project.
 */

const lang = Object.freeze({
  name: 'usd',
  scopeName: 'source.usd',
  displayName: 'USD',
  fileTypes: ['usd', 'usda', 'usdc', 'usdz'],
  aliases: undefined,
  patterns: [
    { include: '#keywords' },
    { include: '#strings' },
    { include: '#storage' },
    { include: '#variables' },
    { include: '#comment' },
    { include: '#number' },
  ],
  repository: {
    keywords: {
      patterns: [
        { name: 'keyword.control.usd', match: /\b(def|over|class|variantSet)\b/dgv },
        { name: 'keyword.operator.usd', match: /\b(add|append|prepend|delete)\b/dgv },
        { name: 'keyword.import.usd', match: /#usda[^\p{L}\p{M}\p{N}\p{Pc}][0-9]+[^\n][0-9]/dgv },
        {
          name: 'keyword.other.usd',
          match:
            /\b(attributes|config|connect|customData|default|dictionary|displayUnit|doc|inherits|kind|mapper|nameChildren|None|offset|payload|permission|prefixSubstitutions|properties|references|relocates|reorder|rootPrims|scale|subLayers|suffixSubstitutions|specializes|symmetryArguments|symmetryFunction|timeSamples|variants|variantSets)\b/dgv,
        },
      ],
    },
    storage: {
      patterns: [
        {
          name: 'storage.type.usd.base',
          match:
            /\b(bool|uchar|int|uint|int64|uint64|half|float|double|string|token|asset|matrix2d|matrix3d|matrix4d|quatd|quatf|quath|double2|float2|half2|int2|double3|float3|half3|int3|double4|float4|half4|int4|rel)\b/dgv,
        },
        {
          name: 'storage.type.usd.ext',
          match:
            /\b(point3d|point3f|point3h|normal3d|normal3f|normal3h|vector3d|vector3f|vector3h|color3d|color3f|color3h|color4d|color4f|color4h|frame4d|texCoord2h|texCoord2d|texCoord2f|texCoord3h|texCoord3d|texCoord3f)\b/dgv,
        },
        { name: 'storage.modifier.usd', match: /\b(varying|uniform|custom)\b/dgv },
      ],
    },
    variables: {
      patterns: [{ name: 'variable.parameter.usda', match: /[a-zA-Z_\:][a-zA-Z0-9_\:]*/dgv }],
    },
    number: {
      patterns: [
        {
          name: 'constant.numeric.float.usda',
          match: /((0(x|X)[0-9a-fA-F]*)|-?(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)/dgv,
        },
      ],
    },
    strings: {
      name: '',
      patterns: [
        { name: 'constant.character.escape.usd', match: /\\[^\n]/dgv },
        {
          name: 'string.quoted.triple.asset.usd',
          begin: /(@@@)/dgv,
          beginCaptures: { '1': { name: 'punctuation.definition.string.begin.asset.usd' } },
          end: /@@@/dgv,
          endCaptures: { '1': { name: 'punctuation.definition.string.end.asset.usd' } },
        },
        { name: 'string.quoted.double.usd', begin: /"/dgv, end: /"/dgv },
        { name: 'string.quoted.double.asset.usd', begin: /@/dgv, end: /@/dgv },
        {
          name: 'string.quoted.double.path.usd',
          begin: /</dgv,
          beginCaptures: { '1': { name: 'punctuation.definition.string.begin.path.usd' } },
          end: />/dgv,
        },
      ],
    },
    comment: {
      patterns: [
        {
          name: 'comment.block.usd',
          begin: /(\/\*)(?:\p{space}*((@)internal)(?=\p{space}|(\*\/)))?/dgv,
          beginCaptures: {
            '1': { name: 'punctuation.definition.comment.usd' },
            '2': { name: 'storage.type.internaldeclaration.usd' },
            '3': { name: 'punctuation.decorator.internaldeclaration.usd' },
          },
          end: /\*\//dgv,
          endCaptures: { '0': { name: 'punctuation.definition.comment.usd' } },
        },
        {
          begin: /(^[ \t]+)?((#)(?:\p{space}*((@)internal)(?=\p{space}|(?=\n?$)))?)/dgv,
          beginCaptures: {
            '1': { name: 'punctuation.whitespace.comment.leading.usd' },
            '2': { name: 'comment.line.double-slash.usd' },
            '3': { name: 'punctuation.definition.comment.usd' },
            '4': { name: 'storage.type.internaldeclaration.usd' },
            '5': { name: 'punctuation.decorator.internaldeclaration.usd' },
          },
          end: /(?=^)/dgv,
          contentName: 'comment.line.hash.usd',
        },
      ],
    },
  },
  embeddedLangs: [],
});

const langs = [lang];

export default langs;
